### ISSUE TITLE
Backend: Empty Subset gives a 500

### ISSUE THREAD

**Issue by d-callan** [VEuPathDB/EdaDataService#110]
@ryanrdoherty think when we added the feature to return a 400 if the request resulted in a too-large response, we broke the feature to return a 400 for an empty subset. 

see stack:
`Caused by: org.veupathdb.service.eda.ds.util.NonEmptyResultStream$EmptyResultException: Requested data stream 'single_tabular_dataset' did not contain any data.
        at org.veupathdb.service.eda.ds.util.NonEmptyResultStream.throwException(NonEmptyResultStream.java:56) ~[service.jar:1.0.0]
        at org.veupathdb.service.eda.ds.util.NonEmptyResultStream.read(NonEmptyResultStream.java:47) ~[service.jar:1.0.0]
        at java.io.FilterInputStream.read(FilterInputStream.java:106) ~[?:?]
        at org.gusdb.fgputil.IoUtil.transferStream(IoUtil.java:204) ~[service.jar:1.0.0]
        at org.veupathdb.service.eda.ds.util.RServeClient.lambda$useRConnectionWithProcessedRemoteFiles$1(RServeClient.java:60) ~[service.jar:1.0.0]
        at org.veupathdb.service.eda.ds.util.RServeClient.useRConnection(RServeClient.java:36) ~[service.jar:1.0.0]
        ... 36 more`

**Comment by ryanrdoherty** [comment]
Yes, we buried the exception in another exception.  Re-exposed.
