### ISSUE TITLE
Back end: Barplot dependency order is missing facetVariable

### ISSUE THREAD

**Issue by bobular** [VEuPathDB/EdaDataService#133]
Seems to be the only one with the problem :)
```
{
	"dataElementDependencyOrder": [
		"xAxisVariable",
		"overlayVariable"
	]
}
```

**Comment by SheenaTomko** [comment]
Faceting in bar plots lets you choose categorical variables, but it also lets you choose a continuous variable and then throws a 500 error. For example, in GEMS1, if you open a bar plot and set x = sex, facet = Water trips per day, you get a 500 error. Reopening for @d-callan to look at.

**Comment by dmfalke** [comment]
The constraint for facet variables is missing the `maxNumValues` property. I think we agreed this would be set to 8 for build 55. Doing so should prevent the above scenario.

**Comment by bobular** [comment]
This may be a duplicate https://github.com/VEuPathDB/EdaNewIssues/issues/78 and maybe this is relevant: https://github.com/VEuPathDB/EdaNewIssues/issues/77

**Comment by d-callan** [comment]
veupathdb/edanewissues#77 and veupathdb/edanewissues#78 are duplicates, and caused as @dmfalke says by my not having yet updated the variable constraints on facets. ill do that now.

**Comment by bobular** [comment]
Nice, thanks - water trips/day works as facet now.

![image](https://user-images.githubusercontent.com/308639/141822086-a5fabfee-545e-4167-ac4f-26ee4d8a5922.png)

**Comment by SheenaTomko** [comment]
@dmfalke, tried to recreate Bob's example above and got the 500 error still. Did this just not make it properly onto the qa site, or is there a new bug?
<img width="831" alt="Screen Shot 2021-11-17 at 1 30 58 PM" src="https://user-images.githubusercontent.com/54597319/142269827-a3709f47-f3bc-400e-a6ff-1c3ce3a99d4e.png">

**Comment by dmfalke** [comment]
There is a new Rserve tag which may contain the fix for this. I will update
qa and let you know when it's been deployed, at which point you can test
again. Thanks, and sorry for the confusion!

**Comment by dmfalke** [comment]
It looks like the latest rserve image is in use now, but I'm still getting a 500.

I just realized this is a different error than what @bobular initially reported. Here is a stack trace that may help

```
2021-11-17 20:11:04.252 [rid:     ] WARN  ErrorMapper:79 - Caught Exception: 
 java.lang.RuntimeException: Unable to complete processing
	at org.veupathdb.service.eda.ds.util.RServeClient.useRConnection(RServeClient.java:41) ~[service.jar:1.0.0]
	at org.veupathdb.service.eda.ds.util.RServeClient.useRConnectionWithProcessedRemoteFiles(RServeClient.java:55) ~[service.jar:1.0.0]
	at org.veupathdb.service.eda.ds.util.RServeClient.useRConnectionWithRemoteFiles(RServeClient.java:51) ~[service.jar:1.0.0]
	at org.veupathdb.service.eda.ds.plugin.pass.BarplotPlugin.writeResults(BarplotPlugin.java:179) ~[service.jar:1.0.0]
	at org.veupathdb.service.eda.ds.plugin.AbstractPlugin.lambda$accept$3(AbstractPlugin.java:133) ~[service.jar:1.0.0]
	at org.gusdb.fgputil.functional.Functions.lambda$cSwallow$4(Functions.java:292) ~[service.jar:1.0.0]
	at org.veupathdb.service.eda.common.client.StreamingDataClient.buildAndProcessStreams(StreamingDataClient.java:56) ~[service.jar:1.0.0]
	at org.veupathdb.service.eda.ds.plugin.AbstractPlugin.accept(AbstractPlugin.java:139) ~[service.jar:1.0.0]
	at org.veupathdb.service.eda.ds.plugin.AbstractPlugin.accept(AbstractPlugin.java:48) ~[service.jar:1.0.0]
	at org.veupathdb.service.eda.generated.model.BarplotPostResponseStream.write(BarplotPostResponseStream.java:21) ~[service.jar:1.0.0]
	at org.glassfish.jersey.message.internal.StreamingOutputProvider.writeTo(StreamingOutputProvider.java:55) ~[service.jar:1.0.0]
	at org.glassfish.jersey.message.internal.StreamingOutputProvider.writeTo(StreamingOutputProvider.java:37) ~[service.jar:1.0.0]
	at org.glassfish.jersey.message.internal.WriterInterceptorExecutor$TerminalWriterInterceptor.invokeWriteTo(WriterInterceptorExecutor.java:242) ~[service.jar:1.0.0]
	at org.glassfish.jersey.message.internal.WriterInterceptorExecutor$TerminalWriterInterceptor.aroundWriteTo(WriterInterceptorExecutor.java:227) ~[service.jar:1.0.0]
	at org.glassfish.jersey.message.internal.WriterInterceptorExecutor.proceed(WriterInterceptorExecutor.java:139) ~[service.jar:1.0.0]
	at org.glassfish.jersey.server.internal.JsonWithPaddingInterceptor.aroundWriteTo(JsonWithPaddingInterceptor.java:85) ~[service.jar:1.0.0]
	at org.glassfish.jersey.message.internal.WriterInterceptorExecutor.proceed(WriterInterceptorExecutor.java:139) ~[service.jar:1.0.0]
	at org.glassfish.jersey.server.internal.MappableExceptionWrapperInterceptor.aroundWriteTo(MappableExceptionWrapperInterceptor.java:61) ~[service.jar:1.0.0]
	at org.glassfish.jersey.message.internal.WriterInterceptorExecutor.proceed(WriterInterceptorExecutor.java:139) ~[service.jar:1.0.0]
	at org.glassfish.jersey.message.internal.MessageBodyFactory.writeTo(MessageBodyFactory.java:1116) ~[service.jar:1.0.0]
	at org.glassfish.jersey.server.ServerRuntime$Responder.writeResponse(ServerRuntime.java:635) ~[service.jar:1.0.0]
	at org.glassfish.jersey.server.ServerRuntime$Responder.processResponse(ServerRuntime.java:373) [service.jar:1.0.0]
	at org.glassfish.jersey.server.ServerRuntime$Responder.process(ServerRuntime.java:363) [service.jar:1.0.0]
	at org.glassfish.jersey.server.ServerRuntime$1.run(ServerRuntime.java:258) [service.jar:1.0.0]
	at org.glassfish.jersey.internal.Errors$1.call(Errors.java:248) [service.jar:1.0.0]
	at org.glassfish.jersey.internal.Errors$1.call(Errors.java:244) [service.jar:1.0.0]
	at org.glassfish.jersey.internal.Errors.process(Errors.java:292) [service.jar:1.0.0]
	at org.glassfish.jersey.internal.Errors.process(Errors.java:274) [service.jar:1.0.0]
	at org.glassfish.jersey.internal.Errors.process(Errors.java:244) [service.jar:1.0.0]
	at org.glassfish.jersey.process.internal.RequestScope.runInScope(RequestScope.java:265) [service.jar:1.0.0]
	at org.glassfish.jersey.server.ServerRuntime.process(ServerRuntime.java:234) [service.jar:1.0.0]
	at org.glassfish.jersey.server.ApplicationHandler.handle(ApplicationHandler.java:680) [service.jar:1.0.0]
	at org.glassfish.jersey.grizzly2.httpserver.GrizzlyHttpContainer.service(GrizzlyHttpContainer.java:356) [service.jar:1.0.0]
	at org.glassfish.grizzly.http.server.HttpHandler$1.run(HttpHandler.java:200) [service.jar:1.0.0]
	at org.glassfish.grizzly.threadpool.AbstractThreadPool$Worker.doWork(AbstractThreadPool.java:569) [service.jar:1.0.0]
	at org.glassfish.grizzly.threadpool.AbstractThreadPool$Worker.run(AbstractThreadPool.java:549) [service.jar:1.0.0]
	at java.lang.Thread.run(Thread.java:832) [?:?]
Caused by: org.rosuda.REngine.Rserve.RserveException: eval failed, request status: error code: 127
	at org.rosuda.REngine.Rserve.RConnection.eval(RConnection.java:261) ~[service.jar:1.0.0]
	at org.veupathdb.service.eda.ds.util.RServeClient.streamResult(RServeClient.java:114) ~[service.jar:1.0.0]
	at org.veupathdb.service.eda.ds.plugin.pass.BarplotPlugin.lambda$writeResults$0(BarplotPlugin.java:191) ~[service.jar:1.0.0]
	at org.veupathdb.service.eda.ds.util.RServeClient.lambda$useRConnectionWithProcessedRemoteFiles$1(RServeClient.java:78) ~[service.jar:1.0.0]
	at org.veupathdb.service.eda.ds.util.RServeClient.useRConnection(RServeClient.java:37) ~[service.jar:1.0.0]
	... 36 more
```

This may need a new issue. Tagging @d-callan

**Comment by SheenaTomko** [comment]
Marking this as complete now. Retested and the variable used to facet previously is no longer available since it has >8 values. Faceting by another variable with the appropriate number of values works correctly
