### ISSUE TITLE
Visualisations: Faceted Scatterplot causes `users/.../analyses` saved analysis update to return a 500 

### ISSUE THREAD

**Issue by bobular** [VEuPathDB/EdaDataService#135]
I'm guessing this is something to do with the size of the thumbnail data.

To reproduce (only reproducible on my dev instance, not through beta.clinepidb.org - possibly due to the involvement of the proxy, see below):

GEMS1
No subsetting
Scatterplot: weight vs mean height **best line fit with raw**
Facet on country (or even a binary variable) and you should get errors that include

```
Unhandled Rejection (Error): 500 Internal Server Error
Error occured while trying to proxy: localhost:3000/users/578013513/analyses/PuxDtIq
```

You can kill the error modal and continue (slowly) - so add a subsetting filter for just Mozambique and you should see the errors stop happening.

Actually on beta I notice that a lot of the back end requests to https://beta.clinepidb.org/eda/users/xxxxx/analyses/c1e3ac4 are taking a long time (minutes!)

**Comment by d-callan** [comment]
stack trace:
`EdaUserService:  org.veupathdb.lib.container.jaxrs.errors.UnprocessableEntityException: HTTP 422 
EdaUserService: 	at org.veupathdb.lib.container.jaxrs.server.middleware.JacksonFilter.readFrom(JacksonFilter.java:141) ~[service.jar:1.0.0]
EdaUserService: 	at org.glassfish.jersey.message.internal.ReaderInterceptorExecutor$TerminalReaderInterceptor.invokeReadFrom(ReaderInterceptorExecutor.java:233) ~[service.jar:1.0.0]
EdaUserService: 	at org.glassfish.jersey.message.internal.ReaderInterceptorExecutor$TerminalReaderInterceptor.aroundReadFrom(ReaderInterceptorExecutor.java:212) ~[service.jar:1.0.0]
EdaUserService: 	at org.glassfish.jersey.message.internal.ReaderInterceptorExecutor.proceed(ReaderInterceptorExecutor.java:132) ~[service.jar:1.0.0]
EdaUserService: 	at org.glassfish.jersey.server.internal.MappableExceptionWrapperInterceptor.aroundReadFrom(MappableExceptionWrapperInterceptor.java:49) ~[service.jar:1.0.0]
EdaUserService: 	at org.glassfish.jersey.message.internal.ReaderInterceptorExecutor.proceed(ReaderInterceptorExecutor.java:132) ~[service.jar:1.0.0]
EdaUserService: 	at org.glassfish.jersey.message.internal.MessageBodyFactory.readFrom(MessageBodyFactory.java:1072) ~[service.jar:1.0.0]
EdaUserService: 	at org.glassfish.jersey.message.internal.InboundMessageContext.readEntity(InboundMessageContext.java:885) ~[service.jar:1.0.0]
EdaUserService: 	at org.glassfish.jersey.server.ContainerRequest.readEntity(ContainerRequest.java:282) ~[service.jar:1.0.0]
EdaUserService: 	at org.glassfish.jersey.server.internal.inject.EntityParamValueParamProvider$EntityValueSupplier.apply(EntityParamValueParamProvider.java:73) ~[service.jar:1.0.0]
EdaUserService: 	at org.glassfish.jersey.server.internal.inject.EntityParamValueParamProvider$EntityValueSupplier.apply(EntityParamValueParamProvider.java:56) ~[service.jar:1.0.0]
EdaUserService: 	at org.glassfish.jersey.server.spi.internal.ParamValueFactoryWithSource.apply(ParamValueFactoryWithSource.java:50) ~[service.jar:1.0.0]
EdaUserService: 	at org.glassfish.jersey.server.spi.internal.ParameterValueHelper.getParameterValues(ParameterValueHelper.java:68) ~[service.jar:1.0.0]
EdaUserService: 	at org.glassfish.jersey.server.model.internal.JavaResourceMethodDispatcherProvider$AbstractMethodParamInvoker.getParamValues(JavaResourceMethodDispatcherProvider.java:109) ~[service.jar:1.0.0]
EdaUserService: 	at org.glassfish.jersey.server.model.internal.JavaResourceMethodDispatcherProvider$ResponseOutInvoker.doDispatch(JavaResourceMethodDispatcherProvider.java:176) ~[service.jar:1.0.0]
EdaUserService: 	at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher.dispatch(AbstractJavaResourceMethodDispatcher.java:79) ~[service.jar:1.0.0]
EdaUserService: 	at org.glassfish.jersey.server.model.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:475) ~[service.jar:1.0.0]
EdaUserService: 	at org.glassfish.jersey.server.model.ResourceMethodInvoker.apply(ResourceMethodInvoker.java:397) ~[service.jar:1.0.0]
EdaUserService: 	at org.glassfish.jersey.server.model.ResourceMethodInvoker.apply(ResourceMethodInvoker.java:81) ~[service.jar:1.0.0]
EdaUserService: 	at org.glassfish.jersey.server.ServerRuntime$1.run(ServerRuntime.java:255) [service.jar:1.0.0]
EdaUserService: 	at org.glassfish.jersey.internal.Errors$1.call(Errors.java:248) [service.jar:1.0.0]
EdaUserService: 	at org.glassfish.jersey.internal.Errors$1.call(Errors.java:244) [service.jar:1.0.0]
EdaUserService: 	at org.glassfish.jersey.internal.Errors.process(Errors.java:292) [service.jar:1.0.0]
EdaUserService: 	at org.glassfish.jersey.internal.Errors.process(Errors.java:274) [service.jar:1.0.0]
EdaUserService: 	at org.glassfish.jersey.internal.Errors.process(Errors.java:244) [service.jar:1.0.0]
EdaUserService: 	at org.glassfish.jersey.process.internal.RequestScope.runInScope(RequestScope.java:265) [service.jar:1.0.0]
EdaUserService: 	at org.glassfish.jersey.server.ServerRuntime.process(ServerRuntime.java:234) [service.jar:1.0.0]
EdaUserService: 	at org.glassfish.jersey.server.ApplicationHandler.handle(ApplicationHandler.java:680) [service.jar:1.0.0]
EdaUserService: 	at org.glassfish.jersey.grizzly2.httpserver.GrizzlyHttpContainer.service(GrizzlyHttpContainer.java:356) [service.jar:1.0.0]
EdaUserService: 	at org.glassfish.grizzly.http.server.HttpHandler$1.run(HttpHandler.java:200) [service.jar:1.0.0]
EdaUserService: 	at org.glassfish.grizzly.threadpool.AbstractThreadPool$Worker.doWork(AbstractThreadPool.java:569) [service.jar:1.0.0]
EdaUserService: 	at org.glassfish.grizzly.threadpool.AbstractThreadPool$Worker.run(AbstractThreadPool.java:549) [service.jar:1.0.0]
EdaUserService: 	at java.lang.Thread.run(Thread.java:832) [?:?]
EdaUserService: 2021-12-15 09:25:13.582 [rid:3oAWZ] DEBUG RequestLogger:42 - Request end: PATCH /users/310666460/analyses/0assIV6 422`

**Comment by bobular** [comment]
Confirming this is still a bug!

**Comment by bobular** [comment]
Adding one filter (e.g. case/control) seems to avoid the problem so it could be a payload issue.
Though I note that with filtering on case/control==case, the thumbnail only contains one sub-plot:
![image](https://user-images.githubusercontent.com/308639/155347206-8d7cdb4f-d064-4c0e-9806-3b22f2ded6ad.png)

If I turn off the actual datapoints using the scatterplot UI, the thumbnail works again
![image](https://user-images.githubusercontent.com/308639/155347404-e33c890d-0e97-48c7-87bc-94b6990412c6.png)

I suspect that if I cancel the filter, the analyses will save properly: Yes it does!

Therefore its something to do with the size of the (presumably SVG-ish) thumbnail images.  This may be something we can address.
