### ISSUE TITLE
numeric-histogram-bin-width fails for some variables

### ISSUE THREAD

**Issue by dmfalke** [VEuPathDB/EdaDataService#15]
The following request results in an HTTP 500 response code:
```sh
curl 'https://dfalke-b.clinepidb.org/eda-data/apps/pass/visualizations/numeric-histogram-bin-width' \
  -H 'Content-Type: application/json' \
  --data '{"studyId":"GEMSCC0002-1","filters":[],"config":{"outputEntityId":"PCO_0000024","valueSpec":"count","xAxisVariable":{"entityId":"PCO_0000024","variableId":"EUPATH_0000025"}}}'
```

Relevant logs:
```
2021-03-19 19:39:16.363 [rid:     ] WARN  ErrorMapper:79 - Caught Exception: 
 java.lang.RuntimeException: Unable to complete processing
        at org.veupathdb.service.eda.ds.util.RServeClient.useRConnection(RServeClient.java:23) ~[service.jar:1.0.0]
        at org.veupathdb.service.eda.ds.util.RServeClient.useRConnectionWithRemoteFiles(RServeClient.java:33) ~[service.jar:1.0.0]
        at org.veupathdb.service.eda.ds.plugin.NumericHistogramBinWidthPlugin.writeResults(NumericHistogramBinWidthPlugin.java:89) ~[service.jar:1.0.0]
        at org.veupathdb.service.eda.ds.plugin.AbstractPlugin.lambda$accept$2(AbstractPlugin.java:96) ~[service.jar:1.0.0]
        at org.gusdb.fgputil.functional.Functions.lambda$cSwallow$4(Functions.java:288) ~[service.jar:1.0.0]
        at org.veupathdb.service.eda.common.client.StreamingDataClient.buildAndProcessStreams(StreamingDataClient.java:58) ~[service.jar:1.0.0]
        at org.veupathdb.service.eda.ds.plugin.AbstractPlugin.accept(AbstractPlugin.java:100) ~[service.jar:1.0.0]
        at org.veupathdb.service.eda.ds.plugin.AbstractPlugin.accept(AbstractPlugin.java:35) ~[service.jar:1.0.0]
        at org.veupathdb.service.eda.generated.model.NumericHistogramBinWidthPostResponseStream.write(NumericHistogramBinWidthPostResponseStream.java:21) ~[service.jar:1.0.0]
        at org.glassfish.jersey.message.internal.StreamingOutputProvider.writeTo(StreamingOutputProvider.java:55) ~[service.jar:1.0.0]
        at org.glassfish.jersey.message.internal.StreamingOutputProvider.writeTo(StreamingOutputProvider.java:37) ~[service.jar:1.0.0]
        at org.glassfish.jersey.message.internal.WriterInterceptorExecutor$TerminalWriterInterceptor.invokeWriteTo(WriterInterceptorExecutor.java:242) ~[service.jar:1.0.0]
        at org.glassfish.jersey.message.internal.WriterInterceptorExecutor$TerminalWriterInterceptor.aroundWriteTo(WriterInterceptorExecutor.java:227) ~[service.jar:1.0.0]
        at org.glassfish.jersey.message.internal.WriterInterceptorExecutor.proceed(WriterInterceptorExecutor.java:139) ~[service.jar:1.0.0]
        at org.glassfish.jersey.server.internal.JsonWithPaddingInterceptor.aroundWriteTo(JsonWithPaddingInterceptor.java:85) ~[service.jar:1.0.0]
        at org.glassfish.jersey.message.internal.WriterInterceptorExecutor.proceed(WriterInterceptorExecutor.java:139) ~[service.jar:1.0.0]
        at org.glassfish.jersey.server.internal.MappableExceptionWrapperInterceptor.aroundWriteTo(MappableExceptionWrapperInterceptor.java:61) ~[service.jar:1.0.0]
        at org.glassfish.jersey.message.internal.WriterInterceptorExecutor.proceed(WriterInterceptorExecutor.java:139) ~[service.jar:1.0.0]
        at org.glassfish.jersey.message.internal.MessageBodyFactory.writeTo(MessageBodyFactory.java:1116) ~[service.jar:1.0.0]
        at org.glassfish.jersey.server.ServerRuntime$Responder.writeResponse(ServerRuntime.java:635) ~[service.jar:1.0.0]
        at org.glassfish.jersey.server.ServerRuntime$Responder.processResponse(ServerRuntime.java:373) [service.jar:1.0.0]
        at org.glassfish.jersey.server.ServerRuntime$Responder.process(ServerRuntime.java:363) [service.jar:1.0.0]
        at org.glassfish.jersey.server.ServerRuntime$1.run(ServerRuntime.java:258) [service.jar:1.0.0]
        at org.glassfish.jersey.internal.Errors$1.call(Errors.java:248) [service.jar:1.0.0]
        at org.glassfish.jersey.internal.Errors$1.call(Errors.java:244) [service.jar:1.0.0]
        at org.glassfish.jersey.internal.Errors.process(Errors.java:292) [service.jar:1.0.0]
        at org.glassfish.jersey.internal.Errors.process(Errors.java:274) [service.jar:1.0.0]
        at org.glassfish.jersey.internal.Errors.process(Errors.java:244) [service.jar:1.0.0]
        at org.glassfish.jersey.process.internal.RequestScope.runInScope(RequestScope.java:265) [service.jar:1.0.0]
        at org.glassfish.jersey.server.ServerRuntime.process(ServerRuntime.java:234) [service.jar:1.0.0]
        at org.glassfish.jersey.server.ApplicationHandler.handle(ApplicationHandler.java:680) [service.jar:1.0.0]
        at org.glassfish.jersey.grizzly2.httpserver.GrizzlyHttpContainer.service(GrizzlyHttpContainer.java:356) [service.jar:1.0.0]
        at org.glassfish.grizzly.http.server.HttpHandler$1.run(HttpHandler.java:200) [service.jar:1.0.0]
        at org.glassfish.grizzly.threadpool.AbstractThreadPool$Worker.doWork(AbstractThreadPool.java:569) [service.jar:1.0.0]
        at org.glassfish.grizzly.threadpool.AbstractThreadPool$Worker.run(AbstractThreadPool.java:549) [service.jar:1.0.0]
        at java.lang.Thread.run(Thread.java:832) [?:?]
Caused by: org.rosuda.REngine.Rserve.RserveException: eval failed, request status: error code: 127
        at org.rosuda.REngine.Rserve.RConnection.eval(RConnection.java:261) ~[service.jar:1.0.0]
        at org.veupathdb.service.eda.ds.plugin.NumericHistogramBinWidthPlugin.lambda$writeResults$0(NumericHistogramBinWidthPlugin.java:114) ~[service.jar:1.0.0]
        at org.veupathdb.service.eda.ds.util.RServeClient.lambda$useRConnectionWithRemoteFiles$0(RServeClient.java:41) ~[service.jar:1.0.0]
        at org.veupathdb.service.eda.ds.util.RServeClient.useRConnection(RServeClient.java:20) ~[service.jar:1.0.0]
        ... 35 more
2021-03-19 19:39:16.364 [rid:     ] WARN  RequestLogger:41 - Request end: POST /apps/pass/visualizations/numeric-histogram-bin-width 500
```

**Comment by d-callan** [comment]
this was a bug in adjusting the binning to the default viewport. should now be resolved (plot.data v0.3.5).
