### ISSUE TITLE
`map-markers` endpoint is giving a 500 if there is missing data

### ISSUE THREAD

**Issue by bobular** [VEuPathDB/EdaDataService#202]
In Study **Jilinde Prospective Cohort**

Map visualization: any variable overlay.

Presumably this is due to missing lat/long values, because adding a subsetting filter on latitude variable solves the problem temporarily.

```
ESC[mESC[33m2022-08-12 11:33:28.243 [rid:     ] WARN  ErrorMapper:79 - Caught Exception: 
ESC[m java.lang.NumberFormatException: empty String
        at jdk.internal.math.FloatingDecimal.readJavaFormatString(FloatingDecimal.java:1842) ~[?:?]
        at jdk.internal.math.FloatingDecimal.parseDouble(FloatingDecimal.java:110) ~[?:?]
        at java.lang.Double.parseDouble(Double.java:651) ~[?:?]
        at java.lang.Double.valueOf(Double.java:614) ~[?:?]
        at org.veupathdb.service.eda.ds.plugin.pass.MapPlugin.writeResults(MapPlugin.java:141) ~[service.jar:3.0.0]
        at org.veupathdb.service.eda.ds.plugin.AbstractPlugin.lambda$accept$3(AbstractPlugin.java:152) ~[service.jar:3.0.0]
        at org.gusdb.fgputil.functional.Functions.lambda$cSwallow$4(Functions.java:292) ~[service.jar:3.0.0]
        at org.veupathdb.service.eda.common.client.StreamingDataClient.buildAndProcessStreams(StreamingDataClient.java:47) ~[
service.jar:3.0.0]
```

**Comment by bobular** [comment]
Hi @ryanrdoherty,

I think in MapPlugin.java from L138, the latitude and longitude conversions need to be inside the conditional statement, and testing for `!= ""` on those columns would be good too.

```
    // loop through rows of data stream, aggregating stats into a map from aggregate value to stats object
    Map<String, GeoVarData> aggregator = new HashMap<>();
    while (s.hasNextLine()) {
      String[] row = parser.parseLineToArray(s.nextLine());
      Double latitude = Double.valueOf(row[latIndex]);
      Double longitude = Double.valueOf(row[lonIndex]);
      
      // entity records counts not impacted by viewport
      if (!(row[geoVarIndex] == null || row[geoVarIndex].equals(""))) { 
        entityRecordsWithGeoVar++;
      
        if (withinViewport(viewport, latitude, longitude)) {
          aggregator.putIfAbsent(row[geoVarIndex], new GeoVarData());
          aggregator.get(row[geoVarIndex]).addRow(Double.valueOf(row[latIndex]), Double.valueOf(row[lonIndex]));
        }
      }  
    }
```

**Comment by bobular** [comment]
Hi @ryanrdoherty - merged, tagged, deployed and (wait 5 mins and) it works! Thanks for your help with this 😄

**Comment by SheenaTomko** [comment]
Looks great
