### ISSUE TITLE
Abundance scatterplot error

### ISSUE THREAD

**Issue by asizemore** [VEuPathDB/EdaDataService#247]
Error below from ann's dev site. QA site also gives 500 but it is different ("Unable to fetch all required data")

<img width="574" alt="Screen Shot 2023-02-17 at 10 45 59 AM" src="https://user-images.githubusercontent.com/11710234/219700190-d968c1a8-1240-46c2-af69-c9d6ebbe083d.png">

```
java.lang.IndexOutOfBoundsException: toIndex = 8
	at java.util.AbstractList.subListRangeCheck(AbstractList.java:507) ~[?:?]
	at java.util.ArrayList.subList(ArrayList.java:1108) ~[?:?]
	at org.veupathdb.service.eda.ds.plugin.abundance.AbundanceScatterplotPlugin.writeResults(AbundanceScatterplotPlugin.java:119) ~[service.jar:3.0.0]
	at org.veupathdb.service.eda.ds.plugin.AbstractPlugin.lambda$accept$5(AbstractPlugin.java:184) ~[service.jar:3.0.0]
	at org.gusdb.fgputil.functional.Functions.lambda$cSwallow$4(Functions.java:293) ~[service.jar:3.0.0]
	at org.veupathdb.service.eda.common.client.StreamingDataClient.buildAndProcessStreams(StreamingDataClient.java:46) ~[service.jar:3.0.0]
	at org.veupathdb.service.eda.ds.plugin.AbstractPlugin.accept(AbstractPlugin.java:190) ~[service.jar:3.0.0]
	at org.veupathdb.service.eda.ds.plugin.AbstractPlugin.accept(AbstractPlugin.java:52) ~[service.jar:3.0.0]
	at org.veupathdb.service.eda.generated.model.ScatterplotPostResponseStream.write(ScatterplotPostResponseStream.java:21) ~[service.jar:3.0.0]
	at org.glassfish.jersey.message.internal.StreamingOutputProvider.writeTo(StreamingOutputProvider.java:55) ~[service.jar:3.0.0]
	at org.glassfish.jersey.message.internal.StreamingOutputProvider.writeTo(StreamingOutputProvider.java:37) ~[service.jar:3.0.0]
	at org.glassfish.jersey.message.internal.WriterInterceptorExecutor$TerminalWriterInterceptor.invokeWriteTo(WriterInterceptorExecutor.java:242) ~[service.jar:3.0.0]
	at org.glassfish.jersey.message.internal.WriterInterceptorExecutor$TerminalWriterInterceptor.aroundWriteTo(WriterInterceptorExecutor.java:227) ~[service.jar:3.0.0]
	at org.glassfish.jersey.message.internal.WriterInterceptorExecutor.proceed(WriterInterceptorExecutor.java:139) ~[service.jar:3.0.0]
	at org.glassfish.jersey.server.internal.JsonWithPaddingInterceptor.aroundWriteTo(JsonWithPaddingInterceptor.java:85) ~[service.jar:3.0.0]
	at org.glassfish.jersey.message.internal.WriterInterceptorExecutor.proceed(WriterInterceptorExecutor.java:139) ~[service.jar:3.0.0]
	at org.glassfish.jersey.server.internal.MappableExceptionWrapperInterceptor.aroundWriteTo(MappableExceptionWrapperInterceptor.java:61) ~[service.jar:3.0.0]
	at org.glassfish.jersey.message.internal.WriterInterceptorExecutor.proceed(WriterInterceptorExecutor.java:139) ~[service.jar:3.0.0]
	at org.veupathdb.lib.container.jaxrs.server.middleware.PrometheusFilter.aroundWriteTo(PrometheusFilter.java:111) ~[service.jar:3.0.0]
	at org.glassfish.jersey.message.internal.WriterInterceptorExecutor.proceed(WriterInterceptorExecutor.java:139) ~[service.jar:3.0.0]
	at org.veupathdb.lib.container.jaxrs.server.middleware.RequestIdFilter.aroundWriteTo(RequestIdFilter.java:70) ~[service.jar:3.0.0]
	at org.glassfish.jersey.message.internal.WriterInterceptorExecutor.proceed(WriterInterceptorExecutor.java:139) ~[service.jar:3.0.0]
	at org.glassfish.jersey.message.internal.MessageBodyFactory.writeTo(MessageBodyFactory.java:1116) ~[service.jar:3.0.0]
	at org.glassfish.jersey.server.ServerRuntime$Responder.writeResponse(ServerRuntime.java:677) ~[service.jar:3.0.0]
	at org.glassfish.jersey.server.ServerRuntime$Responder.processResponse(ServerRuntime.java:385) ~[service.jar:3.0.0]
	at org.glassfish.jersey.server.ServerRuntime$Responder.process(ServerRuntime.java:375) ~[service.jar:3.0.0]
	at org.glassfish.jersey.server.ServerRuntime$1.run(ServerRuntime.java:264) ~[service.jar:3.0.0]
	at org.glassfish.jersey.internal.Errors$1.call(Errors.java:248) ~[service.jar:3.0.0]
	at org.glassfish.jersey.internal.Errors$1.call(Errors.java:244) ~[service.jar:3.0.0]
	at org.glassfish.jersey.internal.Errors.process(Errors.java:292) ~[service.jar:3.0.0]
	at org.glassfish.jersey.internal.Errors.process(Errors.java:274) ~[service.jar:3.0.0]
	at org.glassfish.jersey.internal.Errors.process(Errors.java:244) ~[service.jar:3.0.0]
	at org.glassfish.jersey.process.internal.RequestScope.runInScope(RequestScope.java:265) ~[service.jar:3.0.0]
	at org.glassfish.jersey.server.ServerRuntime.process(ServerRuntime.java:240) ~[service.jar:3.0.0]
	at org.glassfish.jersey.server.ApplicationHandler.handle(ApplicationHandler.java:697) ~[service.jar:3.0.0]
	at org.glassfish.jersey.grizzly2.httpserver.GrizzlyHttpContainer.service(GrizzlyHttpContainer.java:367) ~[service.jar:3.0.0]
	at org.glassfish.grizzly.http.server.HttpHandler$1.run(HttpHandler.java:190) ~[service.jar:3.0.0]
	at org.glassfish.grizzly.threadpool.AbstractThreadPool$Worker.doWork(AbstractThreadPool.java:535) ~[service.jar:3.0.0]
	at org.glassfish.grizzly.threadpool.AbstractThreadPool$Worker.run(AbstractThreadPool.java:515) ~[service.jar:3.0.0]
	at java.lang.Thread.run(Thread.java:831) ~[?:?]
2023-02-17 10:39:23.077 [rid:     ] WARN  PrometheusFilter:136 - Request end: POST /apps/abundance/visualizations/scatterplot 500
```

**Comment by d-callan** [comment]
this is likely bc we assume we will see 8 values, and are actually getting fewer than that from the compute service.

**Comment by d-callan** [comment]
should be fixed w data service v5.5.3

**Comment by asizemore** [comment]
Works on my dev site. Will go update tagger now!

**Comment by SheenaTomko** [comment]
Looks good
