### ISSUE TITLE
Fix categorical map marker overlay NPE

### ISSUE THREAD

**Issue by dmgaldi** [VEuPathDB/EdaDataService#303]
Currently, missing data results in a an NPE for the categorical map overlays due to a missing null check in the `QualitativeOverlayAggregator`.

**Comment by dmgaldi** [comment]
```
ESC[mESC[33m2023-08-04 12:22:23.935 [rid:     ] WARN  ErrorMapper:70 - Caught Exception:
ESC[m java.lang.NumberFormatException: For input string: "2022-02-13T00:00:00"
        at jdk.internal.math.FloatingDecimal.readJavaFormatString(FloatingDecimal.java:2054) ~[?:?]
        at jdk.internal.math.FloatingDecimal.parseDouble(FloatingDecimal.java:110) ~[?:?]
        at java.lang.Double.parseDouble(Double.java:651) ~[?:?]
        at org.veupathdb.service.eda.ds.plugin.standalonemap.markers.ContinuousAggregators$2.addValue(ContinuousAggregators.java:49) ~[service.jar:3.0.0]
        at org.veupathdb.service.eda.ds.plugin.standalonemap.BubbleMapMarkersLegendPlugin.writeResults(BubbleMapMarkersLegendPlugin.java:131) ~[service.jar:3.0.0]
        at org.veupathdb.service.eda.ds.plugin.AbstractPlugin.lambda$accept$5(AbstractPlugin.java:192) ~[service.jar:3.0.0]
        at org.gusdb.fgputil.functional.Functions.lambda$cSwallow$4(Functions.java:293) ~[service.jar:3.0.0]
        at org.veupathdb.service.eda.common.client.StreamingDataClient.buildAndProcessStreams(StreamingDataClient.java:46) ~[service.jar:3.0.0]
        at org.veupathdb.service.eda.ds.plugin.AbstractPlugin.accept(AbstractPlugin.java:198) ~[service.jar:3.0.0]
        at org.veupathdb.service.eda.ds.plugin.AbstractPlugin.accept(AbstractPlugin.java:53) ~[service.jar:3.0.0]
        at org.veupathdb.service.eda.generated.model.StandaloneMapBubblesLegendPostResponseStream.write(StandaloneMapBubblesLegendPostResponseStream.java:21) ~[service.jar:3.0.0]
        at org.glassfish.jersey.message.internal.StreamingOutputProvider.writeTo(StreamingOutputProvider.java:55) ~[service.jar:3.0.0]
        at org.glassfish.jersey.message.internal.StreamingOutputProvider.writeTo(StreamingOutputProvider.java:37) ~[service.jar:3.0.0]
        at org.glassfish.jersey.message.internal.WriterInterceptorExecutor$TerminalWriterInterceptor.invokeWriteTo(WriterInterceptorExecutor.java:242) ~[service.jar:3.0.0]
        at org.glassfish.jersey.message.internal.WriterInterceptorExecutor$TerminalWriterInterceptor.aroundWriteTo(WriterInterceptorExecutor.java:227) ~[service.jar:3.0.0]
        at org.glassfish.jersey.message.internal.WriterInterceptorExecutor.proceed(WriterInterceptorExecutor.java:139) ~[service.jar:3.0.0]
        at org.glassfish.jersey.server.internal.JsonWithPaddingInterceptor.aroundWriteTo(JsonWithPaddingInterceptor.java:85) ~[service.jar:3.0.0]
        at org.glassfish.jersey.message.internal.WriterInterceptorExecutor.proceed(WriterInterceptorExecutor.java:139) ~[service.jar:3.0.0]
        at org.glassfish.jersey.server.internal.MappableExceptionWrapperInterceptor.aroundWriteTo(MappableExceptionWrapperInterceptor.java:61) ~[service.jar:3.0.0]
        at org.glassfish.jersey.message.internal.WriterInterceptorExecutor.proceed(WriterInterceptorExecutor.java:139) ~[service.jar:3.0.0]
        at org.veupathdb.lib.container.jaxrs.server.middleware.PrometheusFilter.aroundWriteTo(PrometheusFilter.java:111) ~[service.jar:3.0.0]
        at org.glassfish.jersey.message.internal.WriterInterceptorExecutor.proceed(WriterInterceptorExecutor.java:139) ~[service.jar:3.0.0]
        at org.veupathdb.lib.container.jaxrs.server.middleware.RequestIdFilter.aroundWriteTo(RequestIdFilter.java:70) ~[service.jar:3.0.0]
```

**Comment by dmgaldi** [comment]
```
Error: Unexpected backend type(s) encountered: Invalid value `undefined` supplied to overlayValue (type: number) of 1 (type: { overlayValue: number }) of 5 (type: ({ geoAggregateValue: string, entityCount: number, avgLat: number, avgLon: number, minLat: number, minLon: number, maxLat: number, maxLon: number } & { overlayValue: number })) of mapElements (type: Array<({ geoAggregateValue: string, entityCount: number, avgLat: number, avgLon: number, minLat: number, minLon: number, maxLat: number, maxLon: number } & { overlayValue: number })>) of [root] (type: { mapElements: Array<({ geoAggregateValue: string, entityCount: number, avgLat: number, avgLon: number, minLat: number, minLon: number, maxLat: number, maxLon: number } & { overlayValue: number })> }) Invalid value `undefined` supplied to overlayValue (type: number) of 1 (type: { overlayValue: number }) of 6 (type: ({ geoAggregateValue: string, entityCount: number, avgLat: number, avgLon: number, minLat: number, minLon: number, maxLat: number, maxLon: number } & { overlayValue: number })) of mapElements (type: Array<({ geoAggregateValue: string, entityCount: number, avgLat: number, avgLon: number, minLat: number, minLon: number, maxLat: number, maxLon: number } & { overlayValue: number })>) of [root] (type: { mapElements: Array<({ geoAggregateValue: string, entityCount: number, avgLat: number, avgLon: number, minLat: number, minLon: number, maxLat: number, maxLon: number } & { overlayValue: number })> })
```

**Comment by dmgaldi** [comment]
In eda_alpha data on fir



```
2023-08-15 10:47:27.165 [rid:3bed6688e51149a18bbe9d8f806a2590] DEBUG PrometheusFilter:136 - Request end: POST /apps/standalone-map/visualizations/map-markers/bubbles/legend 200
2023-08-15 10:47:27.165 [rid:   ] WARN ErrorMapper:70 - Caught Exception: 
 java.lang.NullPointerException: null
	at java.util.Objects.requireNonNull(Objects.java:208) ~[?:?]
	at java.util.Optional.of(Optional.java:113) ~[?:?]
	at java.util.stream.ReduceOps$2ReducingSink.get(ReduceOps.java:129) ~[?:?]
```
