### ISSUE TITLE
Fix date format exception bug in bubble marker plugin

### ISSUE THREAD

**Issue by dmgaldi** [VEuPathDB/EdaDataService#304]
```
ESC[mESC[33m2023-08-04 12:22:23.935 [rid:     ] WARN  ErrorMapper:70 - Caught Exception:
ESC[m java.lang.NumberFormatException: For input string: "2022-02-13T00:00:00"
        at jdk.internal.math.FloatingDecimal.readJavaFormatString(FloatingDecimal.java:2054) ~[?:?]
        at jdk.internal.math.FloatingDecimal.parseDouble(FloatingDecimal.java:110) ~[?:?]
        at java.lang.Double.parseDouble(Double.java:651) ~[?:?]
        at org.veupathdb.service.eda.ds.plugin.standalonemap.markers.ContinuousAggregators$2.addValue(ContinuousAggregators.java:49) ~[service.jar:3.0.0]
        at org.veupathdb.service.eda.ds.plugin.standalonemap.BubbleMapMarkersLegendPlugin.writeResults(BubbleMapMarkersLegendPlugin.java:131) ~[service.jar:3.0.0]
        at org.veupathdb.service.eda.ds.plugin.AbstractPlugin.lambda$accept$5(AbstractPlugin.java:192) ~[service.jar:3.0.0]
        at org.gusdb.fgputil.functional.Functions.lambda$cSwallow$4(Functions.java:293) ~[service.jar:3.0.0]
        at org.veupathdb.service.eda.common.client.StreamingDataClient.buildAndProcessStreams(StreamingDataClient.java:46) ~[service.jar:3.0.0]
        at org.veupathdb.service.eda.ds.plugin.AbstractPlugin.accept(AbstractPlugin.java:198) ~[service.jar:3.0.0]
        at org.veupathdb.service.eda.ds.plugin.AbstractPlugin.accept(AbstractPlugin.java:53) ~[service.jar:3.0.0]
        at org.veupathdb.service.eda.generated.model.StandaloneMapBubblesLegendPostResponseStream.write(StandaloneMapBubblesLegendPostResponseStream.java:21) ~[service.jar:3.0.0]
        at org.glassfish.jersey.message.internal.StreamingOutputProvider.writeTo(StreamingOutputProvider.java:55) ~[service.jar:3.0.0]
        at org.glassfish.jersey.message.internal.StreamingOutputProvider.writeTo(StreamingOutputProvider.java:37) ~[service.jar:3.0.0]
        at org.glassfish.jersey.message.internal.WriterInterceptorExecutor$TerminalWriterInterceptor.invokeWriteTo(WriterInterceptorExecutor.java:242) ~[service.jar:3.0.0]
        at org.glassfish.jersey.message.internal.WriterInterceptorExecutor$TerminalWriterInterceptor.aroundWriteTo(WriterInterceptorExecutor.java:227) ~[service.jar:3.0.0]
        at org.glassfish.jersey.message.internal.WriterInterceptorExecutor.proceed(WriterInterceptorExecutor.java:139) ~[service.jar:3.0.0]
        at org.glassfish.jersey.server.internal.JsonWithPaddingInterceptor.aroundWriteTo(JsonWithPaddingInterceptor.java:85) ~[service.jar:3.0.0]
        at org.glassfish.jersey.message.internal.WriterInterceptorExecutor.proceed(WriterInterceptorExecutor.java:139) ~[service.jar:3.0.0]
        at org.glassfish.jersey.server.internal.MappableExceptionWrapperInterceptor.aroundWriteTo(MappableExceptionWrapperInterceptor.java:61) ~[service.jar:3.0.0]
        at org.glassfish.jersey.message.internal.WriterInterceptorExecutor.proceed(WriterInterceptorExecutor.java:139) ~[service.jar:3.0.0]
        at org.veupathdb.lib.container.jaxrs.server.middleware.PrometheusFilter.aroundWriteTo(PrometheusFilter.java:111) ~[service.jar:3.0.0]
        at org.glassfish.jersey.message.internal.WriterInterceptorExecutor.proceed(WriterInterceptorExecutor.java:139) ~[service.jar:3.0.0]
        at org.veupathdb.lib.container.jaxrs.server.middleware.RequestIdFilter.aroundWriteTo(RequestIdFilter.java:70) ~[service.jar:3.0.0]
```

**Comment by dmgaldi** [comment]
PR:  https://github.com/VEuPathDB/EdaDataService/pull/309/files

**Comment by bobular** [comment]
Adding myself for the front end work. Will add a (draft?) PR soon.
