### ISSUE TITLE
MAP qa.vb (b66) using date with donut marker, std dev produces error

### ISSUE THREAD

**Issue by aurreco-uga** [VEuPathDB/EdaDataService#330]
the UX is a constantly loading page (the snapshot captures only a little bit of the red turning wheel)

data service logs

```
2023-11-13 14:35:18.931 [rid:d69f533e4e74444a85aa4d9483ef7a95] INFO AbstractPlugin:189 - Building and processing 1 required data streams.
2023-11-13 14:35:18.931 [rid:d69f533e4e74444a85aa4d9483ef7a95] INFO ClientUtil:77 - Will send following POST request to [http://merging-internal:80/merging-internal/query](http://merging-internal/merging-internal/query)
{"studyId":"VBP_MEGA","derivedVariables":[],"filters":[],"entityId":"OBI_0000659","outputVariables":[{"entityId":"GAZ_00000448","variableId":"EUPATH_0043205"},{"entityId":"GAZ_00000448","variableId":"OBI_0001620"},{"entityId":"GAZ_00000448","variableId":"OBI_0001621"},{"entityId":"OBI_0000659","variableId":"EUPATH_0043256"}]}
2023-11-13 14:35:20.990 [rid:d69f533e4e74444a85aa4d9483ef7a95] DEBUG PrometheusFilter:165 - Request end: POST /apps/standalone-map/visualizations/map-markers 200
2023-11-13 14:35:20.990 [rid:   ] WARN ErrorMapper:70 - Caught Exception: 
 java.lang.IllegalArgumentException: The variable value 6.62688E11 is not in any specified bin range.
	at org.veupathdb.service.eda.ds.plugin.standalonemap.markers.OverlaySpecification.lambda$recodeNumeric$8(OverlaySpecification.java:145) ~[service.jar:3.0.0]
	at java.util.Optional.orElseThrow(Optional.java:403) ~[?:?]
	at org.veupathdb.service.eda.ds.plugin.standalonemap.markers.OverlaySpecification.recodeNumeric(OverlaySpecification.java:145) ~[service.jar:3.0.0]
```

![donut-date-stddev-bug](https://github.com/VEuPathDB/EdaDataService/assets/16354313/5c89ca87-626f-43d3-92c5-7736ee3f9b80)

**Comment by aurreco-uga** [comment]
seems fixed
