### ISSUE TITLE
Investigate duplicate columns 400 from merging service

### ISSUE THREAD

**Issue by dmgaldi** [VEuPathDB/EdaDataService#345]
## Error
On Watermelon

```
ESC[mESC[33m2024-01-08 19:30:08.504 [rid:     ] WARN  ErrorMapper:70 - Caught Exception:
ESC[m java.lang.RuntimeException: Unable to fetch all required data
        at org.veupathdb.service.eda.common.client.StreamingDataClient.buildDataStreams(StreamingDataClient.java:78) ~[service.jar:3.0.0]
        at org.veupathdb.service.eda.common.client.StreamingDataClient.buildAndProcessStreams(StreamingDataClient.java:38) ~[service.jar:3.0.0]
        at org.veupathdb.service.eda.ds.core.AbstractPlugin.lambda$processRequest$6(AbstractPlugin.java:190) ~[service.jar:3.0.0]
        at org.veupathdb.service.eda.generated.model.BoxplotPostResponseStream.write(BoxplotPostResponseStream.java:21) ~[service.jar:3.0.0]
        at org.glassfish.jersey.message.internal.StreamingOutputProvider.writeTo(StreamingOutputProvider.java:55) ~[service.jar:3.0.0]
        at org.glassfish.jersey.message.internal.StreamingOutputProvider.writeTo(StreamingOutputProvider.java:37) ~[service.jar:3.0.0]
        at org.glassfish.jersey.message.internal.WriterInterceptorExecutor$TerminalWriterInterceptor.invokeWriteTo(WriterInterceptorExecutor.java:242) ~[service.jar:3.0.0]
        at org.glassfish.jersey.message.internal.WriterInterceptorExecutor$TerminalWriterInterceptor.aroundWriteTo(WriterInterceptorExecutor.java:227) ~[service.jar:3.0.0]
        at org.glassfish.jersey.message.internal.WriterInterceptorExecutor.proceed(WriterInterceptorExecutor.java:139) ~[service.jar:3.0.0]
        at org.glassfish.jersey.server.internal.JsonWithPaddingInterceptor.aroundWriteTo(JsonWithPaddingInterceptor.java:85) ~[service.jar:3.0.0]
        at org.glassfish.jersey.message.internal.WriterInterceptorExecutor.proceed(WriterInterceptorExecutor.java:139) ~[service.jar:3.0.0]
        at org.glassfish.jersey.server.internal.MappableExceptionWrapperInterceptor.aroundWriteTo(MappableExceptionWrapperInterceptor.java:61) ~[service.jar:3.0.0]
        at org.glassfish.jersey.message.internal.WriterInterceptorExecutor.proceed(WriterInterceptorExecutor.java:139) ~[service.jar:3.0.0]
        at org.veupathdb.lib.container.jaxrs.server.middleware.PrometheusFilter.aroundWriteTo(PrometheusFilter.java:135) ~[service.jar:3.0.0]
        at org.glassfish.jersey.message.internal.WriterInterceptorExecutor.proceed(WriterInterceptorExecutor.java:139) ~[service.jar:3.0.0]
        at org.veupathdb.lib.container.jaxrs.server.middleware.RequestIdFilter.aroundWriteTo(RequestIdFilter.java:70) ~[service.jar:3.0.0]
        at org.glassfish.jersey.message.internal.WriterInterceptorExecutor.proceed(WriterInterceptorExecutor.java:139) ~[service.jar:3.0.0]
        at org.glassfish.jersey.message.internal.MessageBodyFactory.writeTo(MessageBodyFactory.java:1116) ~[service.jar:3.0.0]
        at org.glassfish.jersey.server.ServerRuntime$Responder.writeResponse(ServerRuntime.java:677) [service.jar:3.0.0]
        at org.glassfish.jersey.server.ServerRuntime$Responder.processResponse(ServerRuntime.java:385) [service.jar:3.0.0]
        at org.glassfish.jersey.server.ServerRuntime$Responder.process(ServerRuntime.java:375) [service.jar:3.0.0]
        at org.glassfish.jersey.server.ServerRuntime$1.run(ServerRuntime.java:264) [service.jar:3.0.0]
        at org.glassfish.jersey.internal.Errors$1.call(Errors.java:248) [service.jar:3.0.0]
        at org.glassfish.jersey.internal.Errors$1.call(Errors.java:244) [service.jar:3.0.0]
        at org.glassfish.jersey.internal.Errors.process(Errors.java:292) [service.jar:3.0.0]
        at org.glassfish.jersey.internal.Errors.process(Errors.java:274) [service.jar:3.0.0]
        at org.glassfish.jersey.internal.Errors.process(Errors.java:244) [service.jar:3.0.0]
        at org.glassfish.jersey.process.internal.RequestScope.runInScope(RequestScope.java:265) [service.jar:3.0.0]
        at org.glassfish.jersey.server.ServerRuntime.process(ServerRuntime.java:240) [service.jar:3.0.0]
        at org.glassfish.jersey.server.ApplicationHandler.handle(ApplicationHandler.java:697) [service.jar:3.0.0]
        at org.glassfish.jersey.grizzly2.httpserver.GrizzlyHttpContainer.service(GrizzlyHttpContainer.java:367) [service.jar:3.0.0]
        at org.glassfish.grizzly.http.server.HttpHandler$1.run(HttpHandler.java:190) [service.jar:3.0.0]
        at org.glassfish.grizzly.threadpool.AbstractThreadPool$Worker.doWork(AbstractThreadPool.java:535) [service.jar:3.0.0]
        at org.glassfish.grizzly.threadpool.AbstractThreadPool$Worker.run(AbstractThreadPool.java:515) [service.jar:3.0.0]
        at java.lang.Thread.run(Thread.java:831) [?:?]
Caused by: java.lang.RuntimeException: 400 Bad Request: {"status":"bad-request","message":"{\"keyedErrors\":{},\"validationLevel\":\"RUNNABLE\",\"validationStatus\":\"FAILED\",\"errors\":[\"Output variables (columns) must be distinct.  Column 'MBIOTEMP_S
ource.EUPATH_0009252_d__Bacteria_p__Firmicutes' is specified more than once.\"]}"}
        at org.gusdb.fgputil.client.ResponseFuture.lambda$getInputStream$0(ResponseFuture.java:49) ~[service.jar:3.0.0]
        at java.util.Optional.orElseThrow(Optional.java:403) ~[?:?]
        at org.gusdb.fgputil.functional.Either.leftOrElseThrow(Either.java:149) ~[service.jar:3.0.0]
        at org.gusdb.fgputil.client.ResponseFuture.getInputStream(ResponseFuture.java:48) ~[service.jar:3.0.0]
        at org.veupathdb.service.eda.common.client.StreamingDataClient.buildDataStreams(StreamingDataClient.java:64) ~[service.jar:3.0.0]
        ... 34 more
```

## Info
It's possible the output variable is the same as a compute spec which could be an issue with the plugin.

**Comment by dmgaldi** [comment]
I was able to reproduce
<img width="1754" alt="Screenshot 2024-01-09 at 4 13 13 PM" src="https://github.com/VEuPathDB/EdaDataService/assets/3497580/1013c310-478d-4bba-a995-3d4e7541de8e">

**Comment by aurreco-uga** [comment]
this could be due to the bug we discovered around biom var names duplicated because of the wacky algorithm  shortening/generating them
