### ISSUE TITLE
500 should be a 400

### ISSUE THREAD

**Issue by aurreco-uga** [VEuPathDB/EdaDataService#365]
ideally we should tell the client what is wrong with their request. 

....
2024-03-29 15:17:40.535 [rid:     ] WARN  ErrorMapper:70 - Caught Exception:
java.lang.NumberFormatException: For input string: "Vienna"
        at jdk.internal.math.FloatingDecimal.readJavaFormatString(FloatingDecimal.java:2054) ~[?:?]
        at jdk.internal.math.FloatingDecimal.parseDouble(FloatingDecimal.java:110) ~[?:?]
        at java.lang.Double.parseDouble(Double.java:651) ~[?:?]
        at org.veupathdb.service.eda.ds.plugin.pass.MapPlugin.writeResults(MapPlugin.java:133) ~[service.jar:3.0.0]
        at org.veupathdb.service.eda.ds.core.AbstractPlugin.lambda$processRequest$5(AbstractPlugin.java:192) ~[service.jar:3.0.0]
        at org.gusdb.fgputil.functional.Functions.lambda$cSwallow$4(Functions.java:293) ~[service.jar:3.0.0]
        at org.veupathdb.service.eda.common.client.StreamingDataClient.processDataStreams(StreamingDataClient.java:52) ~[service.jar:3.0.0]
.....
2024-03-29 15:17:40.536 [rid:     ] WARN  PrometheusFilter:165 - Request end: POST /apps/pass/visualizations/map-markers 500

**Comment by aurreco-uga** [comment]
dan slacks:
The reason Data service can't distinguish whether a downstream error is from Subsetting or Merging is because it doesn't know whether Merging threw an error because of Subsetting. After EDA consolidation, when we hopefully update the data -> merging -> subsetting flow to be intra-process, we should be able to tell where the issue was in the stack trace.

**Comment by aurreco-uga** [comment]
closing, will come back if important
