### ISSUE TITLE
Umsp timeout

### ISSUE THREAD

**Issue by d-callan** [VEuPathDB/EdaDataService#62]
if i make the following request:
 '{"studyId":"UMSP00001-1","filters":[],"config":{"outputEntityId":"EUPATH_0000096","valueSpec":"raw","xAxisVariable":{"entityId":"EUPATH_0000096","variableId":"OBI_0001169"},"yAxisVariable":{"entityId":"EUPATH_0000096","variableId":"EUPATH_0004991"}}}'
to this endpoint:
 /apps/pass/visualizations/scatterplot
it gives an error that i believe suggests something is timing out:
 ESC[mESC[32m2021-07-23 19:12:37.788 [rid:     ] INFO  RServeClient:48 - All data
  streams transferred.
 Jul 23, 2021 7:13:14 PM org.glassfish.jersey.server.ServerRuntime$Responder writ
 eResponse
 SEVERE: An I/O error has occurred while writing a response message entity to the
  container output stream.
 org.glassfish.jersey.server.internal.process.MappableException: java.lang.Runtim
 eException: Unable to complete processing

i know a few things:
1) rserve received the needed data from the data service
2) rserve does not err
3) the request works if i try it locally and wo docker ( i havent tried locally w docker to know)
4) the request fails on the deployed services on ash
5) i cant guarantee, but have reason to believe, the error occurs when rserve goes to write a response back to the data service

**Comment by d-callan** [comment]
it works locally for me w docker compose as well..

**Comment by d-callan** [comment]
from ash: 

> [dcallan@ash:~]$ docker --version
Docker version 19.03.8, build afacb8b
[dcallan@ash:~]$ docker-compose --version
docker-compose version 1.25.1, build a82fef07

from my machine:

> dcallan@L10889:~$ docker --version
Docker version 19.03.13, build cd8016b6bc
dcallan@L10889:~$ docker-compose --version
docker-compose version 1.25.5, build unknown

**Comment by d-callan** [comment]
full stack trace:

SEVERE: An I/O error has occurred while writing a response message entity to the container output stream.
org.glassfish.jersey.server.internal.process.MappableException: java.lang.RuntimeException: Unable to complete processing
        at org.glassfish.jersey.server.internal.MappableExceptionWrapperInterceptor.aroundWriteTo(MappableExceptionWrapperInterceptor.java:67)
        at org.glassfish.jersey.message.internal.WriterInterceptorExecutor.proceed(WriterInterceptorExecutor.java:139)
        at org.glassfish.jersey.message.internal.MessageBodyFactory.writeTo(MessageBodyFactory.java:1116)
        at org.glassfish.jersey.server.ServerRuntime$Responder.writeResponse(ServerRuntime.java:635)
        at org.glassfish.jersey.server.ServerRuntime$Responder.processResponse(ServerRuntime.java:373)
        at org.glassfish.jersey.server.ServerRuntime$Responder.process(ServerRuntime.java:363)
        at org.glassfish.jersey.server.ServerRuntime$1.run(ServerRuntime.java:258)
        at org.glassfish.jersey.internal.Errors$1.call(Errors.java:248)
        at org.glassfish.jersey.internal.Errors$1.call(Errors.java:244)
        at org.glassfish.jersey.internal.Errors.process(Errors.java:292)
        at org.glassfish.jersey.internal.Errors.process(Errors.java:274)
        at org.glassfish.jersey.internal.Errors.process(Errors.java:244)
        at org.glassfish.jersey.process.internal.RequestScope.runInScope(RequestScope.java:265)
        at org.glassfish.jersey.server.ServerRuntime.process(ServerRuntime.java:234)
        at org.glassfish.jersey.server.ApplicationHandler.handle(ApplicationHandler.java:680)
        at org.glassfish.jersey.grizzly2.httpserver.GrizzlyHttpContainer.service(GrizzlyHttpContainer.java:356)
        at org.glassfish.grizzly.http.server.HttpHandler$1.run(HttpHandler.java:200)
        at org.glassfish.grizzly.threadpool.AbstractThreadPool$Worker.doWork(AbstractThreadPool.java:569)
        at org.glassfish.grizzly.threadpool.AbstractThreadPool$Worker.run(AbstractThreadPool.java:549)
        at java.base/java.lang.Thread.run(Thread.java:832)
Caused by: java.lang.RuntimeException: Unable to complete processing
        at org.veupathdb.service.eda.ds.util.RServeClient.useRConnection(RServeClient.java:29)
        at org.veupathdb.service.eda.ds.util.RServeClient.useRConnectionWithRemoteFiles(RServeClient.java:39)
        at org.veupathdb.service.eda.ds.plugin.pass.ScatterplotPlugin.writeResults(ScatterplotPlugin.java:121)
        at org.veupathdb.service.eda.ds.plugin.AbstractPlugin.lambda$accept$3(AbstractPlugin.java:133)
        at org.gusdb.fgputil.functional.Functions.lambda$cSwallow$4(Functions.java:290)
        at org.veupathdb.service.eda.common.client.StreamingDataClient.buildAndProcessStreams(StreamingDataClient.java:56)
        at org.veupathdb.service.eda.ds.plugin.AbstractPlugin.accept(AbstractPlugin.java:139)
        at org.veupathdb.service.eda.ds.plugin.AbstractPlugin.accept(AbstractPlugin.java:48)
        at org.veupathdb.service.eda.generated.model.ScatterplotPostResponseStream.write(ScatterplotPostResponseStream.java:21)
        at org.glassfish.jersey.message.internal.StreamingOutputProvider.writeTo(StreamingOutputProvider.java:55)
        at org.glassfish.jersey.message.internal.StreamingOutputProvider.writeTo(StreamingOutputProvider.java:37)
        at org.glassfish.jersey.message.internal.WriterInterceptorExecutor$TerminalWriterInterceptor.invokeWriteTo(WriterInterceptorExecutor.java:242)
        at org.glassfish.jersey.message.internal.WriterInterceptorExecutor$TerminalWriterInterceptor.aroundWriteTo(WriterInterceptorExecutor.java:227)
        at org.glassfish.jersey.message.internal.WriterInterceptorExecutor.proceed(WriterInterceptorExecutor.java:139)
        at org.glassfish.jersey.server.internal.JsonWithPaddingInterceptor.aroundWriteTo(JsonWithPaddingInterceptor.java:85)
        at org.glassfish.jersey.message.internal.WriterInterceptorExecutor.proceed(WriterInterceptorExecutor.java:139)
        at org.glassfish.jersey.server.internal.MappableExceptionWrapperInterceptor.aroundWriteTo(MappableExceptionWrapperInterceptor.java:61)
        ... 19 more
Caused by: java.io.IOException: Connection is closed
        at org.glassfish.grizzly.nio.NIOConnection.assertOpen(NIOConnection.java:441)
        at org.glassfish.grizzly.http.io.OutputBuffer.write(OutputBuffer.java:663)
        at org.glassfish.grizzly.http.server.NIOOutputStreamImpl.write(NIOOutputStreamImpl.java:59)
        at org.glassfish.jersey.message.internal.CommittingOutputStream.write(CommittingOutputStream.java:200)
        at org.glassfish.jersey.message.internal.WriterInterceptorExecutor$UnCloseableOutputStream.write(WriterInterceptorExecutor.java:276)
        at org.gusdb.fgputil.IoUtil.transferStream(IoUtil.java:203)
        at org.veupathdb.service.eda.ds.plugin.pass.ScatterplotPlugin.lambda$writeResults$0(ScatterplotPlugin.java:146)
        at org.veupathdb.service.eda.ds.util.RServeClient.lambda$useRConnectionWithRemoteFiles$0(RServeClient.java:49)
        at org.veupathdb.service.eda.ds.util.RServeClient.useRConnection(RServeClient.java:26)
        ... 35 more
Caused by: java.io.IOException: Broken pipe
        at java.base/sun.nio.ch.FileDispatcherImpl.write0(Native Method)
        at java.base/sun.nio.ch.SocketDispatcher.write(SocketDispatcher.java:62)
        at java.base/sun.nio.ch.IOUtil.writeFromNativeBuffer(IOUtil.java:113)
        at java.base/sun.nio.ch.IOUtil.write(IOUtil.java:58)
        at java.base/sun.nio.ch.IOUtil.write(IOUtil.java:50)
        at java.base/sun.nio.ch.SocketChannelImpl.write(SocketChannelImpl.java:502)
        at org.glassfish.grizzly.nio.transport.TCPNIOUtils.flushByteBuffer(TCPNIOUtils.java:125)
        at org.glassfish.grizzly.nio.transport.TCPNIOUtils.writeCompositeBuffer(TCPNIOUtils.java:64)
        at org.glassfish.grizzly.nio.transport.TCPNIOAsyncQueueWriter.write0(TCPNIOAsyncQueueWriter.java:105)
        at org.glassfish.grizzly.nio.transport.TCPNIOAsyncQueueWriter.write0(TCPNIOAsyncQueueWriter.java:82)
        at org.glassfish.grizzly.nio.AbstractNIOAsyncQueueWriter.write(AbstractNIOAsyncQueueWriter.java:236)
        at org.glassfish.grizzly.nio.AbstractNIOAsyncQueueWriter.write(AbstractNIOAsyncQueueWriter.java:145)
        at org.glassfish.grizzly.nio.AbstractNIOAsyncQueueWriter.write(AbstractNIOAsyncQueueWriter.java:47)
        at org.glassfish.grizzly.nio.transport.TCPNIOTransportFilter.handleWrite(TCPNIOTransportFilter.java:102)
        at org.glassfish.grizzly.filterchain.TransportFilter.handleWrite(TransportFilter.java:167)
        at org.glassfish.grizzly.filterchain.ExecutorResolver$8.execute(ExecutorResolver.java:87)
        at org.glassfish.grizzly.filterchain.DefaultFilterChain.executeFilter(DefaultFilterChain.java:260)
        at org.glassfish.grizzly.filterchain.DefaultFilterChain.executeChainPart(DefaultFilterChain.java:177)
        at org.glassfish.grizzly.filterchain.DefaultFilterChain.execute(DefaultFilterChain.java:109)
        at org.glassfish.grizzly.filterchain.DefaultFilterChain.process(DefaultFilterChain.java:88)
        at org.glassfish.grizzly.ProcessorExecutor.execute(ProcessorExecutor.java:53)
        at org.glassfish.grizzly.filterchain.FilterChainContext.write(FilterChainContext.java:866)
        at org.glassfish.grizzly.filterchain.FilterChainContext.write(FilterChainContext.java:834)
        at org.glassfish.grizzly.http.io.OutputBuffer.flushBuffer(OutputBuffer.java:1068)
        at org.glassfish.grizzly.http.io.OutputBuffer.write(OutputBuffer.java:698)
        ... 42 more

**Comment by d-callan** [comment]
apparently apache is killing it bc it takes > 1 min. so performance improvements should solve the immediate problem. steve also mentioned making the forced timeout 2 min instead.

**Comment by danicahelb** [comment]
assigned to @SheenaTomko for QA

**Comment by SheenaTomko** [comment]
This can be closed. Discussed in EDA UX this week that scatterplots won't graph all data. Other tickets are being made as needed
