### ISSUE TITLE
Bug in scatter plot

### ISSUE THREAD

**Issue by nkittur-uga** [VEuPathDB/EdaDataService#86]
GEMS1- Height vs. Weight scatter plot threw up an error:

<img width="1274" alt="Screen Shot 2021-09-07 at 9 56 54 AM" src="https://user-images.githubusercontent.com/67710160/132364758-c02261d4-7fd9-46fe-84f2-8d187d92ffb0.png">

**Comment by steve-fischer-200** [comment]
here is the stack trace: 

` java.lang.RuntimeException: Unable to fetch all required data
	at org.veupathdb.service.eda.common.client.StreamingDataClient.buildDataStreams(StreamingDataClient.java:90) ~[service.jar:1.0.0]
	at org.veupathdb.service.eda.common.client.StreamingDataClient.buildAndProcessStreams(StreamingDataClient.java:50) ~[service.jar:1.0.0]
	at org.veupathdb.service.eda.ds.plugin.AbstractPlugin.accept(AbstractPlugin.java:139) ~[service.jar:1.0.0]
	at org.veupathdb.service.eda.ds.plugin.AbstractPlugin.accept(AbstractPlugin.java:48) ~[service.jar:1.0.0]
	at org.veupathdb.service.eda.generated.model.ScatterplotPostResponseStream.write(ScatterplotPostResponseStream.java:21) ~[service.jar:1.0.0]
	at org.glassfish.jersey.message.internal.StreamingOutputProvider.writeTo(StreamingOutputProvider.java:55) ~[service.jar:1.0.0]
	at org.glassfish.jersey.message.internal.StreamingOutputProvider.writeTo(StreamingOutputProvider.java:37) ~[service.jar:1.0.0]
	at org.glassfish.jersey.message.internal.WriterInterceptorExecutor$TerminalWriterInterceptor.invokeWriteTo(WriterInterceptorExecutor.java:242) ~[service.jar:1.0.0]
	at org.glassfish.jersey.message.internal.WriterInterceptorExecutor$TerminalWriterInterceptor.aroundWriteTo(WriterInterceptorExecutor.java:227) ~[service.jar:1.0.0]
	at org.glassfish.jersey.message.internal.WriterInterceptorExecutor.proceed(WriterInterceptorExecutor.java:139) ~[service.jar:1.0.0]
	at org.glassfish.jersey.server.internal.JsonWithPaddingInterceptor.aroundWriteTo(JsonWithPaddingInterceptor.java:85) ~[service.jar:1.0.0]
	at org.glassfish.jersey.message.internal.WriterInterceptorExecutor.proceed(WriterInterceptorExecutor.java:139) ~[service.jar:1.0.0]
	at org.glassfish.jersey.server.internal.MappableExceptionWrapperInterceptor.aroundWriteTo(MappableExceptionWrapperInterceptor.java:61) ~[service.jar:1.0.0]
	at org.glassfish.jersey.message.internal.WriterInterceptorExecutor.proceed(WriterInterceptorExecutor.java:139) ~[service.jar:1.0.0]
	at org.glassfish.jersey.message.internal.MessageBodyFactory.writeTo(MessageBodyFactory.java:1116) ~[service.jar:1.0.0]
	at org.glassfish.jersey.server.ServerRuntime$Responder.writeResponse(ServerRuntime.java:635) ~[service.jar:1.0.0]
	at org.glassfish.jersey.server.ServerRuntime$Responder.processResponse(ServerRuntime.java:373) [service.jar:1.0.0]
	at org.glassfish.jersey.server.ServerRuntime$Responder.process(ServerRuntime.java:363) [service.jar:1.0.0]
	at org.glassfish.jersey.server.ServerRuntime$1.run(ServerRuntime.java:258) [service.jar:1.0.0]
	at org.glassfish.jersey.internal.Errors$1.call(Errors.java:248) [service.jar:1.0.0]
	at org.glassfish.jersey.internal.Errors$1.call(Errors.java:244) [service.jar:1.0.0]
	at org.glassfish.jersey.internal.Errors.process(Errors.java:292) [service.jar:1.0.0]
	at org.glassfish.jersey.internal.Errors.process(Errors.java:274) [service.jar:1.0.0]
	at org.glassfish.jersey.internal.Errors.process(Errors.java:244) [service.jar:1.0.0]
	at org.glassfish.jersey.process.internal.RequestScope.runInScope(RequestScope.java:265) [service.jar:1.0.0]
	at org.glassfish.jersey.server.ServerRuntime.process(ServerRuntime.java:234) [service.jar:1.0.0]
	at org.glassfish.jersey.server.ApplicationHandler.handle(ApplicationHandler.java:680) [service.jar:1.0.0]
	at org.glassfish.jersey.grizzly2.httpserver.GrizzlyHttpContainer.service(GrizzlyHttpContainer.java:356) [service.jar:1.0.0]
	at org.glassfish.grizzly.http.server.HttpHandler$1.run(HttpHandler.java:200) [service.jar:1.0.0]
	at org.glassfish.grizzly.threadpool.AbstractThreadPool$Worker.doWork(AbstractThreadPool.java:569) [service.jar:1.0.0]
	at org.glassfish.grizzly.threadpool.AbstractThreadPool$Worker.run(AbstractThreadPool.java:549) [service.jar:1.0.0]
	at java.lang.Thread.run(Thread.java:832) [?:?]
Caused by: java.lang.RuntimeException: 500 Internal Server Error: {"status":"server-error","message":"Unable to fetch all required data","requestId":"3RuaoYrC4p0h3DCx77eTRW"}
	at org.gusdb.fgputil.client.ResponseFuture.lambda$getInputStream$0(ResponseFuture.java:49) ~[service.jar:1.0.0]
	at java.util.Optional.orElseThrow(Optional.java:401) ~[?:?]
	at org.gusdb.fgputil.functional.Either.leftOrElseThrow(Either.java:149) ~[service.jar:1.0.0]
	at org.gusdb.fgputil.client.ResponseFuture.getInputStream(ResponseFuture.java:48) ~[service.jar:1.0.0]
	at org.veupathdb.service.eda.common.client.StreamingDataClient.buildDataStreams(StreamingDataClient.java:76) ~[service.jar:1.0.0]
	... 31 more
`

**Comment by d-callan** [comment]
i think in this case the interesting error/ log was from the subset service: 
`Caused by: java.lang.RuntimeException: Variable found to incorrectly have multiple values: IAO_0000414`

**Comment by d-callan** [comment]
so i guess this is either a data load problem, or not a problem at all really?

**Comment by nkittur-uga** [comment]
Oh, I see, it is still that multi-value issue that was identified last week. This will likely get fixed in the next data load. I'll QA and update here when this study is reloaded.

**Comment by d-callan** [comment]
whats interesting is that it wasnt constrained against? i wonder if @dmfalke  has insight there.

**Comment by dmfalke** [comment]
The client is disallowing all multi valued variables for visualizations. I believe this is what we had agreed on.

**Comment by dmfalke** [comment]
Oh, sorry, I misread @d-callan's comment. I take it the variables has `isMultiValued = false`, but the runtime found multiple values?

**Comment by d-callan** [comment]
hmm youre right. it does claim  `isMultiValued = false`.  is this another data load bug after all then? bc i thought that was inferred? @jaycolin may know..
